# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post_id',
            new_name='post_id',
        ),
    ]
